In [72]:
import pandas
import numpy

df_participent_status = pandas.read_csv('../source_data/Participant_Status.csv')

In [27]:
# print(participant_data.COHORT.value_counts())

In [73]:
# Add new columns

def is_pd(row):
    cohort = row['COHORT']
    if int(cohort) == 1:
        return 1
    else:
        return 0
    
def is_prodromal(row):
    cohort = row['COHORT']
    if int(cohort) == 4:
        return 1
    else:
        return 0

def is_control(row):
    cohort = row['COHORT']
    if int(cohort) == 2:
        return 1
    else:
        return 0

df_participent_status['COHORT_PD'] = df_participent_status.apply(lambda row: is_pd(row), axis=1)
df_participent_status['COHORT_PRODROMAL'] = df_participent_status.apply(lambda row: is_prodromal(row), axis=1)
df_participent_status['COHORT_HC'] = df_participent_status.apply(lambda row: is_control(row), axis=1)

In [70]:
df_participent_status.head()

,PATNO,COHORT,COHORT_DEFINITION,ENROLL_DATE,ENROLL_STATUS,STATUS_DATE,ENROLL_AGE,INEXPAGE,AV133STDY,PPMI_ONLINE_ENROLL,...,ENRLPRKN,ENRLSRDC,ENRLHPSM,ENRLRBD,ENRLLRRK2,ENRLSNCA,ENRLGBA,COHORT_PD,COHORT_PRODROMAL,COHORT_HC
0,3000,2,Healthy Control,02/2011,enrolled,05/2021,69.1,INEXHC,0.0,NO,...,0.0,0.0,0,0,0,0,0,0,0,1
1,3001,1,Parkinson's Disease,03/2011,enrolled,09/2021,65.1,INEXPD,0.0,NO,...,0.0,1.0,0,0,0,0,0,1,0,0
2,3002,1,Parkinson's Disease,03/2011,enrolled,09/2021,67.6,INEXPD,0.0,NO,...,0.0,1.0,0,0,0,0,0,1,0,0
3,3003,1,Parkinson's Disease,04/2011,enrolled,01/2022,56.7,INEXPD,0.0,NO,...,0.0,1.0,0,0,0,0,0,1,0,0
4,3004,2,Healthy Control,04/2011,enrolled,01/2022,59.4,INEXHC,0.0,NO,...,0.0,0.0,0,0,0,0,0,0,0,1

In [81]:
# filter

# 1 = ParkinsonsDisease, 2 = HealthyControl, 4 = Prodromal

df_participant_usable = df_participent_status[df_participent_status['ENROLL_STATUS'].isin(['enrolled','Complete', 'Enrolled','complete']) & df_participent_status['COHORT_DEFINITION'].isin(["Healthy Control", "Parkinson's Disease", "Prodromal"])]

df_participant_data = df_participant_usable[['PATNO','ENROLL_DATE','ENROLL_AGE','COHORT_PD', 'COHORT_PRODROMAL','COHORT_HC']]
df_participant_data.to_csv('../source_data/participant_main.csv')

In [80]:
df_participant_data.head()

   PATNO ENROLL_DATE  ENROLL_AGE  COHORT_PD  COHORT_PRODROMAL  COHORT_HC
0   3000     02/2011        69.1          0                 0          1
1   3001     03/2011        65.1          1                 0          0
2   3002     03/2011        67.6          1                 0          0
3   3003     04/2011        56.7          1                 0          0
4   3004     04/2011        59.4          0                 0          1