In [3]:
import math
import numpy as np
import pandas
from scipy.stats import ttest_ind

original_data = pandas.read_csv('../working_data/updrsiv_all_q_p_s.csv')

original_data.head()

# ditch prev_sigfall

fallers = original_data.query('SIGFALL == 1.0')
fallers = fallers.drop(['PREV_SIGFALL','SIGFALL'], axis=1)
non_fallers = original_data.query('SIGFALL == 0.0')
non_fallers = non_fallers.drop(['PREV_SIGFALL','SIGFALL'], axis=1)

In [7]:
non_fallers.head()

,D_NP4WDYSK,D_NP4WDYSKDEN,D_NP4WDYSKNUM,D_NP4WDYSKPCT,D_NP4DYSKI,D_NP4OFF,D_NP4OFFDEN,D_NP4OFFNUM,D_NP4OFFPCT,D_NP4FLCTI,D_NP4FLCTX,D_NP4DYSTN,D_NP4DYSTNDEN,D_NP4DYSTNNUM,D_NP4DYSTNPCT,D_NP4TOT
0,0.0,2.0,2.0,21.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,4.0,1.0,24.0,0.0,0.0,1.0,1.0,6.0,3.0,1.0,0.0,0.0,1.0,0.0,6.0
2,0.0,0.0,2.0,0.0,0.0,-1.0,-5.0,2.0,-31.0,1.0,0.0,0.0,0.0,-5.0,23.0,0.0
3,1.0,2.0,-2.0,-16.0,0.0,0.0,0.0,-2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,1.0,4.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [11]:
qs = non_fallers.columns

significant_qs = []

for q in qs:
    p = ttest_ind(fallers[q], non_fallers[q], equal_var=False)
    print(q)
    print(p)
    if p.pvalue < 0.05:        
        significant_qs.append(q)

D_NP4WDYSK
Ttest_indResult(statistic=-1.0319682810425392, pvalue=0.3080310397311403)
D_NP4WDYSKDEN
Ttest_indResult(statistic=-1.125818531240104, pvalue=0.2632481335543519)
D_NP4WDYSKNUM
Ttest_indResult(statistic=-0.6959258387761788, pvalue=0.4919216498165363)
D_NP4WDYSKPCT
Ttest_indResult(statistic=-0.9166001971988668, pvalue=0.3622868988499025)
D_NP4DYSKI
Ttest_indResult(statistic=-0.24428644771363994, pvalue=0.8084177605800666)
D_NP4OFF
Ttest_indResult(statistic=-0.7359485915197913, pvalue=0.46677896909057437)
D_NP4OFFDEN
Ttest_indResult(statistic=-0.8567050925287871, pvalue=0.3968375021970658)
D_NP4OFFNUM
Ttest_indResult(statistic=0.04436945729303991, pvalue=0.9648984702868232)
D_NP4OFFPCT
Ttest_indResult(statistic=-0.9476745055747712, pvalue=0.34974446567505846)
D_NP4FLCTI
Ttest_indResult(statistic=0.0, pvalue=1.0)
D_NP4FLCTX
Ttest_indResult(statistic=1.3397062772454214, pvalue=0.1869323414128201)
D_NP4DYSTN
Ttest_indResult(statistic=-0.10955825151614831, pvalue=0.9135640923156956)
D_NP4DYSTNDEN
Ttest_indResult(statistic=-1.1241506109717276, pvalue=0.27009814317372477)
D_NP4DYSTNNUM
Ttest_indResult(statistic=-0.5517771607979405, pvalue=0.584143780203944)
D_NP4DYSTNPCT
Ttest_indResult(statistic=-1.044337447355548, pvalue=0.30593633330787195)
D_NP4TOT
Ttest_indResult(statistic=-0.17774885068544335, pvalue=0.8598272309741359)

In [10]:
significant_qs

[]

In [ ]:
# No significant differences